In [125]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20, 10)
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
import itertools
import csv

# Data Cleaning

In [126]:
MS = pd.read_excel('MS Dataset.xlsx')
MS.head()
MS.shape

(98, 12)

In [127]:
MSval = [1] * 98
MS['MSval'] = MSval
MS.head()

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
0             1.0                        2.0                    35.0   
1             2.0                        2.0                    37.0   
2             3.0                        1.0                    32.0   
3             4.0                        2.0                    39.0   
4             5.0                        2.0                    30.0   

   Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  \
0          2.065              NaN           0.080               NaN       NaN   
1          0.160             8.93           0.039              4.54  0.018000   
2          3.520             8.75           0.448              6.70  0.402286   
3          1.170             9.70           0.010             18.17  0.121000   
4          0.080            11.70           0.190              5.90  0.007000   

   Q Lambda  OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  \
0       NaN                           1.0                             2.0   
1  0.009000                           1.0                             2.0   
2  0.066866                           1.0                             0.0   
3  0.001000                           1.0                             2.0   
4  0.032000                           1.0                             2.0   

   OCB type  MSval  
0       2.0      1  
1       2.0      1  
2       2.0      1  
3       2.0      1  
4       2.0      1

In [128]:
nonMS= pd.read_excel('NonMS Dataset.xlsx')
nonMS.head()

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
0             1.0                        2.0                    26.0   
1             2.0                        2.0                    49.0   
2             3.0                        2.0                    34.0   
3             4.0                        2.0                    26.0   
4             5.0                        2.0                    35.0   

   Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  \
0           0.34             14.1           0.050             10.30  0.024113   
1           0.12              NaN           0.024               NaN       NaN   
2           0.90             13.4           0.090              6.11  0.067164   
3           0.74              NaN           0.010               NaN       NaN   
4           0.23              8.8           0.040             22.10  0.026136   

   Q Lambda  OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  \
0  0.004854                           1.0                             2.0   
1       NaN                           1.0                             2.0   
2  0.014730                           1.0                             2.0   
3       NaN                           1.0                             2.0   
4  0.001810                           1.0                             2.0   

   OCB type  
0       2.0  
1       2.0  
2       2.0  
3       2.0  
4       2.0

In [129]:
nonMS['Patient Number'] = nonMS['Patient Number'] + 98
nonMS.head()

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
0            99.0                        2.0                    26.0   
1           100.0                        2.0                    49.0   
2           101.0                        2.0                    34.0   
3           102.0                        2.0                    26.0   
4           103.0                        2.0                    35.0   

   Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  \
0           0.34             14.1           0.050             10.30  0.024113   
1           0.12              NaN           0.024               NaN       NaN   
2           0.90             13.4           0.090              6.11  0.067164   
3           0.74              NaN           0.010               NaN       NaN   
4           0.23              8.8           0.040             22.10  0.026136   

   Q Lambda  OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  \
0  0.004854                           1.0                             2.0   
1       NaN                           1.0                             2.0   
2  0.014730                           1.0                             2.0   
3       NaN                           1.0                             2.0   
4  0.001810                           1.0                             2.0   

   OCB type  
0       2.0  
1       2.0  
2       2.0  
3       2.0  
4       2.0

In [130]:
nonMSval = [0] * 41
nonMS['MSval'] = nonMSval
nonMS.head()

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
0            99.0                        2.0                    26.0   
1           100.0                        2.0                    49.0   
2           101.0                        2.0                    34.0   
3           102.0                        2.0                    26.0   
4           103.0                        2.0                    35.0   

   Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  \
0           0.34             14.1           0.050             10.30  0.024113   
1           0.12              NaN           0.024               NaN       NaN   
2           0.90             13.4           0.090              6.11  0.067164   
3           0.74              NaN           0.010               NaN       NaN   
4           0.23              8.8           0.040             22.10  0.026136   

   Q Lambda  OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  \
0  0.004854                           1.0                             2.0   
1       NaN                           1.0                             2.0   
2  0.014730                           1.0                             2.0   
3       NaN                           1.0                             2.0   
4  0.001810                           1.0                             2.0   

   OCB type  MSval  
0       2.0      0  
1       2.0      0  
2       2.0      0  
3       2.0      0  
4       2.0      0

In [131]:
df = MS.append(nonMS, ignore_index=True)
df.head(-5)

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
0               1.0                        2.0                    35.0   
1               2.0                        2.0                    37.0   
2               3.0                        1.0                    32.0   
3               4.0                        2.0                    39.0   
4               5.0                        2.0                    30.0   
..              ...                        ...                     ...   
129           130.0                        2.0                    40.0   
130           131.0                        2.0                    32.0   
131           132.0                        2.0                    36.0   
132           133.0                        1.0                    15.0   
133           134.0                        2.0                    25.0   

     Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum  \
0            2.065              NaN           0.080               NaN   
1            0.160             8.93           0.039              4.54   
2            3.520             8.75           0.448              6.70   
3            1.170             9.70           0.010             18.17   
4            0.080            11.70           0.190              5.90   
..             ...              ...             ...               ...   
129          0.040            12.44           0.040              8.03   
130          0.050            15.80           0.050             10.60   
131            NaN              NaN             NaN               NaN   
132          0.110              NaN           0.030               NaN   
133          0.016              NaN           0.110               NaN   

      Q Kappa  Q Lambda  OCB IgG in CSF (1-yes, 2-no)  \
0         NaN       NaN                           1.0   
1    0.018000  0.009000                           1.0   
2    0.402286  0.066866                           1.0   
3    0.121000  0.001000                           1.0   
4    0.007000  0.032000                           1.0   
..        ...       ...                           ...   
129  0.003215  0.004981                           2.0   
130  0.003165  0.004717                           2.0   
131       NaN       NaN                           2.0   
132       NaN       NaN                           2.0   
133       NaN       NaN                           2.0   

     OCB IgG in serum (1-yes, 2-no)  OCB type  MSval  
0                               2.0       2.0      1  
1                               2.0       2.0      1  
2                               0.0       2.0      1  
3                               2.0       2.0      1  
4                               2.0       2.0      1  
..                              ...       ...    ...  
129                             2.0       1.0      0  
130                             2.0       1.0      0  
131                             2.0       1.0      0  
132                             2.0       1.0      0  
133                             2.0       1.0      0  

[134 rows x 13 columns]

In [132]:
df[df.isna().any(axis=1)]

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
0               1.0                        2.0                    35.0   
5               6.0                        1.0                    28.0   
10             11.0                        2.0                    22.0   
11             12.0                        2.0                    54.0   
16             17.0                        2.0                    15.0   
22             23.0                        2.0                     NaN   
28             29.0                        2.0                    30.0   
31             32.0                        2.0                    38.0   
38             39.0                        1.0                    32.0   
39             40.0                        2.0                    43.0   
40             41.0                        1.0                    46.0   
41             42.0                        2.0                    22.0   
43             44.0                        2.0                    47.0   
48             49.0                        2.0                    51.0   
54             55.0                        2.0                    27.0   
62             63.0                        2.0                    29.0   
66             67.0                        2.0                    22.0   
83             84.0                        2.0                     NaN   
89             90.0                        2.0                    18.0   
91             92.0                        2.0                    29.0   
97             98.0                        2.0                     NaN   
99            100.0                        2.0                    49.0   
101           102.0                        2.0                    26.0   
105           106.0                        2.0                    29.0   
106           107.0                        2.0                    26.0   
112           113.0                        2.0                    49.0   
131           132.0                        2.0                    36.0   
132           133.0                        1.0                    15.0   
133           134.0                        2.0                    25.0   
136           137.0                        2.0                     NaN   

     Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum  \
0            2.065              NaN           0.080               NaN   
5            0.263              NaN           0.105               NaN   
10           0.950              NaN           0.100               NaN   
11             NaN              NaN             NaN               NaN   
16             NaN              NaN             NaN               NaN   
22           1.230             5.40           0.050              3.76   
28           0.270              NaN           0.328               NaN   
31             NaN              NaN             NaN               NaN   
38           0.610              NaN           0.412               NaN   
39             NaN              NaN             NaN               NaN   
40           0.560              NaN           0.847               NaN   
41           0.710              NaN           0.260               NaN   
43           0.245              NaN           0.317               NaN   
48           1.430              NaN           0.018               NaN   
54           0.760              NaN           1.700               NaN   
62           0.308              NaN           0.097               NaN   
66           0.370              NaN           0.150               NaN   
83             NaN              NaN             NaN               NaN   
89           0.023              NaN           0.024               NaN   
91           0.200              NaN           0.160               NaN   
97             NaN              NaN             NaN               NaN   
99           0.120              NaN           0.024               NaN   
101          0.740             

In [133]:
df = df.dropna()
df

Patient Number  Gender (1-male, 2-female)  Age at the time of CIS  \
1               2.0                        2.0                    37.0   
2               3.0                        1.0                    32.0   
3               4.0                        2.0                    39.0   
4               5.0                        2.0                    30.0   
6               7.0                        1.0                    17.0   
..              ...                        ...                     ...   
130           131.0                        2.0                    32.0   
134           135.0                        2.0                    48.0   
135           136.0                        2.0                    29.0   
137           138.0                        2.0                    45.0   
138           139.0                        1.0                    38.0   

     Kappa FLC CSF  Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum  \
1            0.160             8.93           0.039              4.54   
2            3.520             8.75           0.448              6.70   
3            1.170             9.70           0.010             18.17   
4            0.080            11.70           0.190              5.90   
6            1.250            13.77           0.630             13.24   
..             ...              ...             ...               ...   
130          0.050            15.80           0.050             10.60   
134          0.024            16.38           0.034              7.25   
135          0.030             9.71           0.003              1.33   
137          0.040            10.80           0.020              8.22   
138          0.050             6.40           0.020              4.50   

      Q Kappa  Q Lambda  OCB IgG in CSF (1-yes, 2-no)  \
1    0.018000  0.009000                           1.0   
2    0.402286  0.066866                           1.0   
3    0.121000  0.001000                           1.0   
4    0.007000  0.032000                           1.0   
6    0.091000  0.048000                           1.0   
..        ...       ...                           ...   
130  0.003165  0.004717                           2.0   
134  0.001465  0.004690                           2.0   
135  0.003090  0.004717                           2.0   
137  0.003704  0.002433                           2.0   
138  0.007812  0.004444                           2.0   

     OCB IgG in serum (1-yes, 2-no)  OCB type  MSval  
1                               2.0       2.0      1  
2                               0.0       2.0      1  
3                               2.0       2.0      1  
4                               2.0       2.0      1  
6                               2.0       2.0      1  
..                              ...       ...    ...  
130                             2.0       1.0      0  
134                             2.0       1.0      0  
135                             2.0       1.0      0  
137                             2.0       1.0      0  
138                             2.0       1.0      0  

[109 rows x 13 columns]

In [134]:
df = df.drop(columns=['Patient Number'])
df

Gender (1-male, 2-female)  Age at the time of CIS  Kappa FLC CSF  \
1                          2.0                    37.0          0.160   
2                          1.0                    32.0          3.520   
3                          2.0                    39.0          1.170   
4                          2.0                    30.0          0.080   
6                          1.0                    17.0          1.250   
..                         ...                     ...            ...   
130                        2.0                    32.0          0.050   
134                        2.0                    48.0          0.024   
135                        2.0                    29.0          0.030   
137                        2.0                    45.0          0.040   
138                        1.0                    38.0          0.050   

     Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  Q Lambda  \
1               8.93           0.039              4.54  0.018000  0.009000   
2               8.75           0.448              6.70  0.402286  0.066866   
3               9.70           0.010             18.17  0.121000  0.001000   
4              11.70           0.190              5.90  0.007000  0.032000   
6              13.77           0.630             13.24  0.091000  0.048000   
..               ...             ...               ...       ...       ...   
130            15.80           0.050             10.60  0.003165  0.004717   
134            16.38           0.034              7.25  0.001465  0.004690   
135             9.71           0.003              1.33  0.003090  0.004717   
137            10.80           0.020              8.22  0.003704  0.002433   
138             6.40           0.020              4.50  0.007812  0.004444   

     OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  OCB type  \
1                             1.0                             2.0       2.0   
2                             1.0                             0.0       2.0   
3                             1.0                             2.0       2.0   
4                             1.0                             2.0       2.0   
6                             1.0                             2.0       2.0   
..                            ...                             ...       ...   
130                           2.0                             2.0       1.0   
134                           2.0                             2.0       1.0   
135                           2.0                             2.0       1.0   
137                           2.0                             2.0       1.0   
138                           2.0                             2.0       1.0   

     MSval  
1        1  
2        1  
3        1  
4        1  
6        1  
..     ...  
130      0  
134      0  
135      0  
137      0  
138      0  

[109 rows x 12 columns]

# ML Stuffs

### Data Cleaning

In [135]:
df

Gender (1-male, 2-female)  Age at the time of CIS  Kappa FLC CSF  \
1                          2.0                    37.0          0.160   
2                          1.0                    32.0          3.520   
3                          2.0                    39.0          1.170   
4                          2.0                    30.0          0.080   
6                          1.0                    17.0          1.250   
..                         ...                     ...            ...   
130                        2.0                    32.0          0.050   
134                        2.0                    48.0          0.024   
135                        2.0                    29.0          0.030   
137                        2.0                    45.0          0.040   
138                        1.0                    38.0          0.050   

     Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  Q Lambda  \
1               8.93           0.039              4.54  0.018000  0.009000   
2               8.75           0.448              6.70  0.402286  0.066866   
3               9.70           0.010             18.17  0.121000  0.001000   
4              11.70           0.190              5.90  0.007000  0.032000   
6              13.77           0.630             13.24  0.091000  0.048000   
..               ...             ...               ...       ...       ...   
130            15.80           0.050             10.60  0.003165  0.004717   
134            16.38           0.034              7.25  0.001465  0.004690   
135             9.71           0.003              1.33  0.003090  0.004717   
137            10.80           0.020              8.22  0.003704  0.002433   
138             6.40           0.020              4.50  0.007812  0.004444   

     OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  OCB type  \
1                             1.0                             2.0       2.0   
2                             1.0                             0.0       2.0   
3                             1.0                             2.0       2.0   
4                             1.0                             2.0       2.0   
6                             1.0                             2.0       2.0   
..                            ...                             ...       ...   
130                           2.0                             2.0       1.0   
134                           2.0                             2.0       1.0   
135                           2.0                             2.0       1.0   
137                           2.0                             2.0       1.0   
138                           2.0                             2.0       1.0   

     MSval  
1        1  
2        1  
3        1  
4        1  
6        1  
..     ...  
130      0  
134      0  
135      0  
137      0  
138      0  

[109 rows x 12 columns]

## Binary Classification

In [136]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [137]:
# Create classifiers
lr = LogisticRegression()
svc = LinearSVC(C = 1.0)
rfc = RandomForestClassifier(n_estimators = 100)

In [138]:
train, test = train_test_split(df, test_size = 0.2)

In [139]:
train.head()

Gender (1-male, 2-female)  Age at the time of CIS  Kappa FLC CSF  \
114                        2.0                    29.0          0.670   
124                        2.0                    50.0          0.031   
130                        2.0                    32.0          0.050   
120                        2.0                    35.0          0.040   
25                         2.0                    22.0          0.422   

     Kappa FCL Serum  Lambda FLC CSF  Lambda FLC Serum   Q Kappa  Q Lambda  \
114            18.50           0.300              9.03  0.036216  0.033223   
124            13.94           0.052              8.81  0.002224  0.005902   
130            15.80           0.050             10.60  0.003165  0.004717   
120            10.80           0.010              7.70  0.003704  0.001299   
25             25.11           0.492             18.07  0.017000  0.027000   

     OCB IgG in CSF (1-yes, 2-no)  OCB IgG in serum (1-yes, 2-no)  OCB type  \
114                           1.0                             2.0       2.0   
124                           2.0                             2.0       1.0   
130                           2.0                             2.0       1.0   
120                           2.0                             2.0       1.0   
25                            1.0                             2.0       2.0   

     MSval  
114      0  
124      0  
130      0  
120      0  
25       1

In [140]:
train_feat = train.iloc[:,:11]  # independent vars
train_targ = train['MSval']

In [141]:
test_feat = test.iloc[:,:11]
test_targ = test['MSval']

### Logistic Regression
2nd best

In [142]:
lr.fit(train_feat, train_targ)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [143]:
lr.score(train_feat, train_targ)

0.8390804597701149

In [144]:
lr.score(test_feat, test_targ)

0.8181818181818182

In [145]:
lr.coef_  # log odds / logits / odds ratio - check these out to get function
np.transpose(lr.coef_)

array([[-0.4614765 ],
       [-0.01162901],
       [ 0.31040345],
       [-0.13188439],
       [ 0.75921272],
       [ 0.20649234],
       [ 0.23126056],
       [ 0.09264156],
       [-1.3229747 ],
       [-0.70170787],
       [ 0.47577822]])

In [146]:
preds = lr.predict(test_feat)

In [147]:
pd.crosstab(preds, test_targ)

MSval  0   1
row_0       
0      5   2
1      2  13

In [148]:
confusion_matrix(lr.predict(train_feat), train_targ)

array([[13,  2],
       [12, 60]])

In [149]:
confusion_matrix(lr.predict(test_feat), test_targ)

array([[ 5,  2],
       [ 2, 13]])

### Linear SVM Model
worst

In [158]:
svc.fit(train_feat, train_targ)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC()

In [159]:
svc.score(train_feat, train_targ)

0.7471264367816092

In [160]:
svc.score(test_feat, test_targ)

0.7727272727272727

In [161]:
np.transpose(svc.coef_)

array([[-0.16092955],
       [ 0.02183029],
       [ 0.07940891],
       [-0.04618165],
       [ 0.68800068],
       [ 0.06225669],
       [ 0.20507936],
       [ 0.05395526],
       [-0.43836982],
       [-0.11723475],
       [ 0.43109145]])

In [162]:
preds = svc.predict(train_feat)

In [163]:
confusion_matrix(svc.predict(train_feat), train_targ)

array([[ 3,  0],
       [22, 62]])

In [164]:
confusion_matrix(svc.predict(test_feat), test_targ)

array([[ 2,  0],
       [ 5, 15]])

### Random Forest Classifier

In [150]:
rfc = RandomForestClassifier(n_estimators = 100)

In [151]:
rfc.fit(train_feat, train_targ)

RandomForestClassifier()

In [152]:
rfc.score(train_feat, train_targ)

1.0

In [153]:
rfc.score(test_feat, test_targ)

0.8636363636363636

In [154]:
rfc.predict(train_feat)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1])

In [155]:
preds = rfc.predict(train_feat)

In [156]:
confusion_matrix(rfc.predict(train_feat), train_targ)

array([[25,  0],
       [ 0, 62]])

In [157]:
confusion_matrix(rfc.predict(test_feat), test_targ)

array([[ 5,  1],
       [ 2, 14]])